apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether.controller.webhookServiceName" . }}
  namespace: {{ include "aether.namespace" . }}
  labels:
    {{- include "aether.controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "aether.controller.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
