{{- if .Values.edge.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aether.edge.serviceAccountName" . }}
  namespace: {{ include "aether.edge.namespace" . }}
  labels:
    {{- include "aether.edge.labels" . | nindent 4 }}
{{- end }}
