apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aether.registrar.serviceAccountName" . }}
  namespace: {{ include "aether.namespace" . }}
  labels:
    {{- include "aether.registrar.labels" . | nindent 4 }}
