apiVersion: v1
kind: Service
metadata:
  name: {{ include "aether.registrar.fullname" . }}
  namespace: {{ include "aether.namespace" . }}
  labels:
    {{- include "aether.registrar.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "aether.registrar.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.registrar.service.port }}
      targetPort: {{ .Values.registrar.service.targetPort }}
      protocol: TCP
