apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aether-registrar
  labels:
    app: aether-registrar
    app.kubernetes.io/name: aether-registrar
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
