"""helm_contract_test: a chart's render compared with the external-harness contract."""

load("@rules_helm//helm:defs.bzl", "HelmPackageInfo")

# Placeholders are @@-delimited so nothing in the script collides with bash's
# own ${...} / $(...) syntax. The environment is the one the //bazel/helm
# runners set: helm keeps its caches, repository list and registry credentials
# under $HOME, and a sandbox has no writable home.
_RUNNER = """\
#!/usr/bin/env bash
# Generated by //test/harnesscontract:defs.bzl helm_contract_test. Do not edit.
set -uo pipefail

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS=@@HELM_PLUGINS@@

exec @@CHECKER@@ --helm @@HELM@@ --chart @@CHART@@ --name @@NAME@@ --ids @@IDS@@
"""

def _shell_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"

def _helm_contract_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart
    checker = ctx.executable._checker

    script = _RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", _shell_quote(toolchain.helm_plugins.short_path)),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@CHECKER@@", _shell_quote(checker.short_path)),
        ("@@NAME@@", _shell_quote(ctx.attr.chart_name)),
        ("@@IDS@@", _shell_quote(",".join(ctx.attr.ids))),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    runfiles = ctx.runfiles(files = [
        chart,
        checker,
        toolchain.helm,
        toolchain.helm_plugins,
    ]).merge(ctx.attr._checker[DefaultInfo].default_runfiles)
    return [DefaultInfo(executable = runner, runfiles = runfiles)]

helm_contract_test = rule(
    doc = """Asserts that a chart renders the objects external-harness.yaml lists for it.

The contract (`charts` in //test/harnesscontract:external-harness.yaml) says,
per chart, which `helm template` to run (release name, namespace, `--set`
pairs) and which objects of that render a harness outside this repository
addresses: workload names and namespaces, pod labels, container names, the
rolling-update strategy. This rule runs those renders with the toolchain's
helm against the packaged chart and compares.

Nothing about the render is written in the BUILD file: the options and the
expectations both come from the contract, so there is one list, and a chart
that renames an object fails here with a message naming that file.

`ids` is the one thing the BUILD file does hold: the ids of the contract's
renders of this chart and of their objects. The test fails when that list and
the contract differ, in either direction, so a render or an object cannot be
removed from the contract while the chart still renders it without this list
changing in the same diff.

The checker never prints a render. It lives outside `charts/` on purpose: a
change to a chart's own BUILD file counts as a chart change and needs a
version bump, and adding a contract entry is not one.
""",
    implementation = _helm_contract_test_impl,
    test = True,
    attrs = {
        "chart": attr.label(
            doc = "The `helm_chart` target to render.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "ids": attr.string_list(
            doc = "The id of every `charts` entry for this chart and of every object under them.",
            mandatory = True,
            allow_empty = False,
        ),
        "chart_name": attr.string(
            doc = "The chart's name in the contract (`chart:` of a `charts` entry).",
            mandatory = True,
        ),
        "_checker": attr.label(
            default = Label("//test/harnesscontract/cmd/chartcheck"),
            executable = True,
            cfg = "target",
        ),
    },
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)
