load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "referencegrant",
    srcs = [
        "backendref.go",
        "referencegrant.go",
    ],
    importpath = "aethermesh.dev/common/referencegrant",
    visibility = ["//visibility:public"],
    deps = [
        "//common/serviceref",
        "@io_k8s_sigs_gateway_api//apis/v1:apis",
        "@io_k8s_sigs_gateway_api//apis/v1beta1",
    ],
)

go_test(
    name = "referencegrant_test",
    size = "small",
    srcs = [
        "backendref_test.go",
        "referencegrant_test.go",
    ],
    embed = [":referencegrant"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_sigs_gateway_api//apis/v1:apis",
        "@io_k8s_sigs_gateway_api//apis/v1beta1",
    ],
)
