#!/usr/bin/env bash
# Generates colima.bazelrc with the resolved Colima Docker socket path.
# Run this once after cloning or when your Colima setup changes.
#
# Usage: ./bazel/configure_colima.sh

set -euo pipefail

COLIMA_SOCK="$HOME/.colima/default/docker.sock"
OUTPUT="colima.bazelrc"

if [[ ! -S "$COLIMA_SOCK" ]]; then
    echo "WARNING: Colima socket not found at $COLIMA_SOCK"
    echo "Start Colima with: colima start"
    echo "Then re-run: ./bazel/configure_colima.sh"
    exit 1
fi

cat > "$OUTPUT" <<EOF
# Auto-generated by bazel/configure_colima.sh — do not edit.
# Re-run ./bazel/configure_colima.sh if your Colima setup changes.
test:colima --sandbox_add_mount_pair=${COLIMA_SOCK}:/var/run/docker.sock
test:colima --test_env=DOCKER_HOST=unix://${COLIMA_SOCK}
test:colima --test_env=TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
EOF

echo "Wrote $OUTPUT (socket: $COLIMA_SOCK)"
