load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "schedmetrics",
    srcs = ["schedmetrics.go"],
    importpath = "aethermesh.dev/agent/internal/schedmetrics",
    visibility = ["//agent:__subpackages__"],
    deps = [
        "//common/procsched",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "schedmetrics_test",
    size = "small",
    srcs = ["schedmetrics_test.go"],
    embed = [":schedmetrics"],
    deps = [
        "//common/procsched",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_sdk_metric//metricdata",
    ],
)
