load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "procsched",
    srcs = ["procsched.go"],
    importpath = "aethermesh.dev/common/procsched",
    visibility = ["//visibility:public"],
)

go_test(
    name = "procsched_test",
    size = "small",
    srcs = ["procsched_test.go"],
    embed = [":procsched"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
