load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "ctrlqueue",
    srcs = ["ctrlqueue.go"],
    importpath = "aethermesh.dev/common/ctrlqueue",
    visibility = ["//visibility:public"],
    deps = [
        "@io_k8s_client_go//util/workqueue",
        "@io_k8s_sigs_controller_runtime//:controller-runtime",
        "@io_k8s_sigs_controller_runtime//pkg/controller",
        "@io_k8s_sigs_controller_runtime//pkg/controller/priorityqueue",
        "@io_k8s_sigs_controller_runtime//pkg/reconcile",
    ],
)

go_test(
    name = "ctrlqueue_test",
    size = "small",
    srcs = ["ctrlqueue_test.go"],
    embed = [":ctrlqueue"],
    deps = [
        "@io_k8s_client_go//util/workqueue",
        "@io_k8s_sigs_controller_runtime//pkg/controller/priorityqueue",
        "@io_k8s_sigs_controller_runtime//pkg/reconcile",
    ],
)
