load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cmd",
    srcs = ["root.go"],
    importpath = "aethermesh.dev/cni/internal/cmd",
    visibility = ["//visibility:public"],
    deps = [
        "//cni/internal/constants",
        "//cni/internal/install",
        "//common/log",
        "@com_github_spf13_cobra//:cobra",
    ],
)

go_test(
    name = "cmd_test",
    srcs = ["root_test.go"],
    embed = [":cmd"],
    deps = ["@com_github_stretchr_testify//assert"],
)
