load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "util",
    srcs = ["watcher.go"],
    importpath = "aethermesh.dev/cni/internal/util",
    visibility = ["//cni:__subpackages__"],
    deps = [
        "//common/file",
        "@com_github_fsnotify_fsnotify//:fsnotify",
    ],
)

go_test(
    name = "util_test",
    srcs = ["watcher_test.go"],
    deps = [
        ":util",
        "@com_github_stretchr_testify//require",
    ],
)
