#!/usr/bin/env bash
# Run //agent/test/envoy_validate against an Envoy binary built OUTSIDE this
# workspace — typically the //proxy workspace's freshly built //:envoy — instead
# of the chart-pinned aether-proxy image the gate uses by default.
#
#   agent/test/envoy_validate/validate-built-proxy.sh <envoy-binary> [bazel test args...]
#
# Why: by default the gate validates against @pinned_envoy_linux_<arch>, the
# binary lifted from the image //charts/aether:values.yaml pins
# (//bazel/proxy_pin). A PR that changes proxy/ (extensions compiled in or out,
# carried patches) would otherwise be checked against the PREVIOUS release, not
# the proxy it builds. proxy.yml runs this on every proxy PR.
#
# Mechanism: --override_repository swaps the host-arch pinned repo for a local
# one whose `envoy` is a symlink to the given binary. The test target, its
# runfiles layout and its lookup are unchanged, and Bazel digests the file the
# symlink resolves to, so a rebuilt binary at the same path re-runs the test
# instead of serving a cached pass. With no override (plain `bazel test`) the
# gate is exactly what it was.
#
# The test logs `envoy under validation: <resolved path> (version: ...)` and
# fails if the binary is not an Envoy (TestEnvoyVersionRejectsNonEnvoy).
set -euo pipefail

if [[ $# -lt 1 ]]; then
	echo "usage: $0 <envoy-binary> [bazel test args...]" >&2
	exit 2
fi

bin="$1"
shift
if [[ ! -f "$bin" || ! -x "$bin" ]]; then
	echo "error: $bin is not an executable file" >&2
	exit 2
fi
bin="$(cd "$(dirname "$bin")" && pwd -P)/$(basename "$bin")"

case "$(uname -m)" in
x86_64 | amd64) arch=amd64 ;;
aarch64 | arm64) arch=arm64 ;;
*)
	echo "error: unsupported host arch $(uname -m)" >&2
	exit 2
	;;
esac

repo="$(mktemp -d "${TMPDIR:-/tmp}/aether-envoy-override.XXXXXX")"
trap 'rm -rf "$repo"' EXIT
: >"$repo/REPO.bazel"
cat >"$repo/BUILD.bazel" <<'EOF'
# Generated by agent/test/envoy_validate/validate-built-proxy.sh.
exports_files(
    ["envoy"],
    visibility = ["//visibility:public"],
)
EOF
ln -s "$bin" "$repo/envoy"

echo "envoy_validate: overriding @pinned_envoy_linux_${arch} with ${bin}"
# Informational only: the test itself is the judge of whether this is an Envoy.
"$bin" --version || echo "envoy_validate: $bin --version failed (exit $?)"

cd "$(dirname "${BASH_SOURCE[0]}")/../../.."
bazel test \
	"--override_repository=+pinned_proxy+pinned_envoy_linux_${arch}=${repo}" \
	--test_output=all \
	--test_arg=-test.v \
	--nocache_test_results \
	"$@" \
	//agent/test/envoy_validate/...
