apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "agent.clusterScopedName" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "agent.clusterScopedName" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "agent.clusterScopedName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "agent.serviceAccountName" . }}
    namespace: {{ include "agent.namespace" . }}
