apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aether-agent.serviceAccountName" . }}
  namespace: {{ include "aether-agent.namespace" . }}
  labels:
    {{- include "aether-agent.labels" . | nindent 4 }}
{{- if .Values.proxy.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aether-agent.proxy.serviceAccountName" . }}
  namespace: {{ include "aether-agent.namespace" . }}
  labels:
    {{- include "aether-agent.proxy.labels" . | nindent 4 }}
{{- end }}
