apiVersion: v1
kind: ConfigMap
metadata:
  name: aether-proxy-config
  namespace: aether-system
data:
  envoy.yaml: |
    admin:
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 9901
    
    dynamic_resources:
      ads_config:
        api_type: DELTA_GRPC
        grpc_services:
          - envoy_grpc:
              cluster_name: xds_server
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    
    static_resources:
      clusters:
      - name: xds_server
        type: STATIC
        load_assignment:
          cluster_name: xds_server
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      pipe:
                        path: /run/aether/xds.sock
        typed_extension_protocol_options:
          envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
            "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
            explicit_http_config:
              http2_protocol_options: {}
