global:
  openshift: false
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
    ingressControllerType: "" # If not openshift, and want to expose services, set to a supported option [ingress-nginx]
    # Update these
    clusterName: talos-main
    trustDomain: aether.internal
    caSubject:
      country: BR
      organization: Aether
      commonName: aether.internal
    persistence:
      storageClass: openebs-hostpath

spiffe-oidc-discovery-provider:
  enabled: false

spire-server:
  controllerManager:
    ignoreNamespaces:
      - kube-system
      - kube-public
      - local-path-storage
      # openshift creates many namespaces that should be typically ignored:
      - openshift-.*
      # ibmcloud specific namespaces:
      - ibm-.*
      - openebs

spire-agent:
  logFormat: json
  sockets:
    admin:
      enabled: true
  authorizedDelegates:
    - spiffe://aether.internal/ns/aether-system/sa/aether-proxy
  sds:
    enabled: true
