global:
  openshift: false
  spire:
    recommendations:
      enabled: true
    namespaces:
      create: true
    ingressControllerType: "" # If not openshift, and want to expose services, set to a supported option [ingress-nginx]
    # Update these
    clusterName: talos-main
    trustDomain: aether.internal
    caSubject:
      country: BR
      organization: Aether
      commonName: aether.internal
    persistence:
      storageClass: openebs-hostpath

spiffe-oidc-discovery-provider:
  enabled: false
