{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "aether-registrar.namespace" . }}
  labels:
    {{- include "aether-registrar.labels" . | nindent 4 }}
{{- end }}
