apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "registrar.serviceAccountName" . }}
  namespace: {{ include "registrar.namespace" . }}
  labels:
    {{- include "registrar.labels" . | nindent 4 }}
