#!/usr/bin/env bash
# Test of scripts/materialize-generated-go.sh against a throwaway git
# repository and a fake `bazel`: no Bazel, no network, no Go. The fake answers
# the script's four calls (query for the proto targets, query for other
# generated Go inputs, build, cquery for the output paths, info) from files the
# cases write, laid out the way rules_go 0.64 lays out `go_generated_srcs`.
#
# What it pins:
#   - files land at <import path minus the module path>/<file>, rules_go's
#     empty `package ignore` stub is skipped, and a second run writes nothing;
#   - a path git tracks is never overwritten, a path .gitignore does not cover
#     is never written, a file without a "Code generated" header is never
#     copied, and a refusal leaves the tree untouched (nothing half-written);
#   - a generated Go input that is not a go_proto_library output fails the run;
#   - a file that is no longer generated is removed on the next run;
#   - --clean removes exactly what was written and nothing hand-written;
#   - --check-untracked fails once a generated file is committed;
#   - go.mod and go.sum are never modified.
#
# The real thing (Bazel builds the six proto packages and the plain go command
# then builds the module) is `make go-build-plain`, and the `go` job of
# .github/workflows/codeql.yaml on every pull request.
#
# Run: bazel test //scripts:materialize_generated_go_test, or
#      bash scripts/materialize_generated_go_test.sh
set -uo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$HERE/materialize-generated-go.sh"
[ -f "$SCRIPT" ] || {
	echo "FAIL: $SCRIPT not found"
	exit 1
}
command -v git >/dev/null || {
	echo "FAIL: git is not on PATH"
	exit 1
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

FAILS=0
pass() { echo "PASS  $*"; }
fail() {
	echo "FAIL  $*"
	FAILS=$((FAILS + 1))
}
# check <description> <command...>: the command must succeed.
check() {
	local what="$1"
	shift
	if "$@"; then pass "$what"; else fail "$what"; fi
}
# absent [-v] <extended regex> <file>: no line of the file matches (with -v: no
# line of the file fails to match).
absent() {
	local invert=()
	if [ "$1" = "-v" ]; then
		invert=(-v)
		shift
	fi
	[ -f "$2" ] || return 1
	! grep -E "${invert[@]}" -- "$1" "$2" >/dev/null
}
# refuse <description> <expected stderr substring> <command...>: the command
# must fail and say why.
refuse() {
	local what="$1" want="$2" out
	shift 2
	if out="$("$@" 2>&1)"; then
		fail "$what: succeeded, wanted a refusal"
	elif [[ "$out" != *"$want"* ]]; then
		fail "$what: refused without '$want': $out"
	else
		pass "$what"
	fi
}

# No user or system git configuration: the result must not depend on the
# machine's identity, hooks or global excludes.
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null
export GIT_AUTHOR_NAME=t GIT_AUTHOR_EMAIL=t@example.invalid
export GIT_COMMITTER_NAME=t GIT_COMMITTER_EMAIL=t@example.invalid

MODULE="example.test/mod"
REPO="$TMP/repo"
EXECROOT="$TMP/execroot"
FAKE="$TMP/fake"
mkdir -p "$REPO" "$EXECROOT" "$FAKE/bin"

# --- the fake bazel -----------------------------------------------------------
cat >"$FAKE/bin/bazel" <<'EOF'
#!/usr/bin/env bash
# Serves canned answers from $FAKE_DIR and logs every invocation.
echo "$*" >>"$FAKE_DIR/calls"
case "$1" in
query)
	case "$*" in
	*'generated file'*) cat "$FAKE_DIR/other" ;;
	*) cat "$FAKE_DIR/targets" ;;
	esac
	;;
build) ;;
cquery) cat "$FAKE_DIR/outputs" ;;
info) echo "$FAKE_EXECROOT" ;;
*)
	echo "fake bazel: unexpected command $1" >&2
	exit 64
	;;
esac
EOF
chmod +x "$FAKE/bin/bazel"
export FAKE_DIR="$FAKE" FAKE_EXECROOT="$EXECROOT" BAZEL="$FAKE/bin/bazel"

# gen <package dir> <target> <file> [body]: one generated output, at the path
# rules_go gives it, read-only like every Bazel output.
OUTBASE="bazel-out/k8-fastbuild/bin"
gen() {
	local pkg="$1" target="$2" file="$3" body="${4:-}"
	local rel="$OUTBASE/$pkg/${target}_/$MODULE/$pkg/$file"
	mkdir -p "$EXECROOT/$(dirname "$rel")"
	rm -f "$EXECROOT/$rel"
	if [ -n "$body" ]; then
		printf '%s\n' "$body" >"$EXECROOT/$rel"
	else
		printf '// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: %s\n\npackage v1\n' "$file" >"$EXECROOT/$rel"
	fi
	chmod 0444 "$EXECROOT/$rel"
	echo "$rel" >>"$FAKE/outputs"
}
STUB=$'// +build ignore\n\npackage ignore'

reset_fake() {
	rm -rf "${EXECROOT:?}/bazel-out"
	: >"$FAKE/outputs"
	: >"$FAKE/other"
	: >"$FAKE/calls"
	printf '%s\n' "//api/aether/a/v1:av1_go_proto" "//api/aether/b/deep/v1:bv1_go_proto" >"$FAKE/targets"
	gen api/aether/a/v1 av1_go_proto a.pb.go
	gen api/aether/a/v1 av1_go_proto a_grpc.pb.go "$STUB"
	gen api/aether/a/v1 av1_go_proto svc.pb.go
	gen api/aether/a/v1 av1_go_proto svc_grpc.pb.go
	gen api/aether/b/deep/v1 bv1_go_proto b.pb.go
}

# --- the throwaway repository -------------------------------------------------
git -C "$REPO" init -q -b main
mkdir -p "$REPO/api/aether/a/v1" "$REPO/api/aether/b/deep/v1" "$REPO/other/v1"
printf 'module %s\n\ngo 1.27.1\n' "$MODULE" >"$REPO/go.mod"
echo "example.test/dep v1.0.0 h1:abc=" >"$REPO/go.sum"
printf '/api/aether/**/*.pb.go\n/.materialized-generated-go\n' >"$REPO/.gitignore"
echo 'syntax = "proto3";' >"$REPO/api/aether/a/v1/a.proto"
printf 'package v1\n\n// hand-written\n' >"$REPO/api/aether/a/v1/doc.go"
git -C "$REPO" add -A
git -C "$REPO" commit -q -m init

run() { (cd "$REPO" && bash "$SCRIPT" "$@"); }
sums() { cat "$REPO/go.mod" "$REPO/go.sum" | cksum; }
SUMS_BEFORE="$(sums)"
MANIFEST="$REPO/.materialized-generated-go"

# --- 1. materialize -----------------------------------------------------------
reset_fake
out="$(run 2>&1)" || fail "first run failed: $out"
check "first run reports 4 written" grep -q '2 target(s), 4 file(s): 4 written, 0 unchanged, 0 stale removed, 1 empty' <<<"$out"
for f in api/aether/a/v1/a.pb.go api/aether/a/v1/svc.pb.go api/aether/a/v1/svc_grpc.pb.go api/aether/b/deep/v1/b.pb.go; do
	check "$f is in the tree" test -f "$REPO/$f"
	check "$f is listed in the manifest" grep -qxF "$f" "$MANIFEST"
	check "$f is writable (a rerun can replace it)" test -w "$REPO/$f"
done
check "the empty rules_go stub is not copied" test ! -e "$REPO/api/aether/a/v1/a_grpc.pb.go"
check "git sees nothing to commit" test -z "$(git -C "$REPO" status --porcelain)"
check "the build asked for the go_generated_srcs output group" grep -q '^build .*--output_groups=go_generated_srcs' "$FAKE/calls"

# --- 2. idempotent --------------------------------------------------------------
stamp="$(stat -c %Y%s "$REPO/api/aether/a/v1/a.pb.go" 2>/dev/null || stat -f %m%z "$REPO/api/aether/a/v1/a.pb.go")"
out="$(run 2>&1)" || fail "second run failed: $out"
check "second run writes nothing" grep -q '4 file(s): 0 written, 4 unchanged' <<<"$out"
check "second run left the file alone" test "$stamp" = "$(stat -c %Y%s "$REPO/api/aether/a/v1/a.pb.go" 2>/dev/null || stat -f %m%z "$REPO/api/aether/a/v1/a.pb.go")"

# --- 3. a changed output is rewritten -------------------------------------------
reset_fake
gen api/aether/b/deep/v1 bv1_go_proto b.pb.go $'// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage v1\n\nvar Changed = 1'
sort -u -o "$FAKE/outputs" "$FAKE/outputs"
out="$(run 2>&1)" || fail "rewrite run failed: $out"
check "a changed output is rewritten" grep -q '1 written, 3 unchanged' <<<"$out"
check "the new content is in the tree" grep -q 'var Changed = 1' "$REPO/api/aether/b/deep/v1/b.pb.go"

# --- 4. a file that is no longer generated is removed ---------------------------
reset_fake
grep -v '/svc_grpc.pb.go$' "$FAKE/outputs" >"$FAKE/outputs.new"
mv "$FAKE/outputs.new" "$FAKE/outputs"
out="$(run 2>&1)" || fail "stale run failed: $out"
check "the stale file is reported" grep -q '1 stale removed' <<<"$out"
check "the stale file is gone" test ! -e "$REPO/api/aether/a/v1/svc_grpc.pb.go"
check "the stale file left the manifest" absent svc_grpc "$MANIFEST"

# --- 5. --clean -----------------------------------------------------------------
out="$(run --clean 2>&1)" || fail "--clean failed: $out"
check "--clean reports 3 removed" grep -q 'removed 3 file(s)' <<<"$out"
check "--clean leaves no generated file" test -z "$(find "$REPO/api" -name '*.pb.go')"
check "--clean removes the manifest" test ! -e "$MANIFEST"
check "--clean keeps the hand-written file" test -f "$REPO/api/aether/a/v1/doc.go"
check "--clean keeps the .proto" test -f "$REPO/api/aether/a/v1/a.proto"
out="$(run --clean 2>&1)" || fail "second --clean failed: $out"
check "--clean with nothing to do succeeds" grep -q 'removed 0 file(s)' <<<"$out"

# --- 6. refusals leave the tree untouched ---------------------------------------
# 6a. a destination git tracks. It sorts LAST among the outputs, so an
# implementation that copied as it went would have written the others already.
reset_fake
printf 'package v1\n\n// hand-written, despite the name\n' >"$REPO/api/aether/b/deep/v1/b.pb.go"
git -C "$REPO" add -f api/aether/b/deep/v1/b.pb.go
git -C "$REPO" commit -q -m "track a file at a generated path"
refuse "a tracked destination is not overwritten" "refusing to overwrite api/aether/b/deep/v1/b.pb.go: git tracks it" run
check "the tracked file is unchanged" grep -q 'hand-written, despite the name' "$REPO/api/aether/b/deep/v1/b.pb.go"
check "nothing was written before the refusal" test ! -e "$REPO/api/aether/a/v1/a.pb.go"
check "no manifest after a refusal" test ! -e "$MANIFEST"
refuse "--check-untracked fails on a committed generated file" "api/aether/b/deep/v1/b.pb.go" run --check-untracked
git -C "$REPO" rm -q -f api/aether/b/deep/v1/b.pb.go
git -C "$REPO" commit -q -m "untrack it"
out="$(run --check-untracked 2>&1)" || fail "--check-untracked failed on a clean repository: $out"
check "--check-untracked passes on a clean repository" grep -q 'no generated Go file is tracked' <<<"$out"

# 6b. a destination .gitignore does not cover.
reset_fake
echo "//other/v1:otherv1_go_proto" >>"$FAKE/targets"
gen other/v1 otherv1_go_proto zz.pb.go
refuse "a destination that is not git-ignored is not written" "other/v1/zz.pb.go is not git-ignored" run
check "the un-ignored file was not written" test ! -e "$REPO/other/v1/zz.pb.go"
check "nothing else was written either" test ! -e "$REPO/api/aether/a/v1/a.pb.go"

# 6c. an output with no generated-code header.
reset_fake
gen api/aether/b/deep/v1 bv1_go_proto zz.pb.go $'package v1\n\nvar NotGenerated = 1'
refuse "an output without a generated header is not copied" "has no 'Code generated ... DO NOT EDIT.' header" run
check "nothing was written before that refusal" test ! -e "$REPO/api/aether/a/v1/a.pb.go"

# 6d. an output that is not under <target>_/<module>/.
reset_fake
mkdir -p "$EXECROOT/$OUTBASE/api/aether/a/v1"
echo "// Code generated by x. DO NOT EDIT." >"$EXECROOT/$OUTBASE/api/aether/a/v1/loose.pb.go"
echo "$OUTBASE/api/aether/a/v1/loose.pb.go" >>"$FAKE/outputs"
refuse "an output outside the import-path layout is rejected" "unexpected generated output" run

# 6e. a generated Go input that is not a proto.
reset_fake
echo "//agent/internal/thing:gen.go" >"$FAKE/other"
refuse "a non-proto generated Go source fails the run" "are sources of a Go rule but are not go_proto_library outputs" run
check "nothing was written with an unhandled generated input" test ! -e "$REPO/api/aether/a/v1/a.pb.go"

# 6f. no targets at all is a failure, not "nothing to do".
reset_fake
: >"$FAKE/targets"
refuse "an empty target query is a failure" "found no go_proto_library" run

# 6g. the proxy workspace is never built.
reset_fake
echo "//proxy/api:x_go_proto" >>"$FAKE/targets"
refuse "a proxy-workspace target is refused" "proxy workspace" run
check "no build ran for the refused set" absent '^build' "$FAKE/calls"

# 6h. an unknown flag.
refuse "an unknown argument is rejected" "unknown argument" run --tidy

# --- 7. go.mod and go.sum ---------------------------------------------------------
check "go.mod and go.sum are byte-identical after every case" test "$SUMS_BEFORE" = "$(sums)"
check "the fake bazel was never asked for anything but query/build/cquery/info" absent -v '^(query|build|cquery|info) ' "$FAKE/calls"

if [ "$FAILS" -ne 0 ]; then
	echo "$FAILS check(s) failed"
	exit 1
fi
echo "PASS: materialize-generated-go"
