apiVersion: v1
kind: Service
metadata:
  name: aether-registrar
  namespace: aether-system
  labels:
    app: aether-registrar
    app.kubernetes.io/name: aether-registrar
spec:
  selector:
    app: aether-registrar
    app.kubernetes.io/name: aether-registrar
  ports:
    - name: grpc
      port: 8443
      targetPort: 8443
      protocol: TCP
