"""Helm rules that rules_helm does not provide: a template-rejection test, a template-absence test and a named-repository chart push."""

load("@rules_helm//helm:defs.bzl", "HelmPackageInfo")

# Placeholders are @@-delimited so nothing in the script collides with bash's
# own ${...} / $(...) syntax.
_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_fail_test. Do not edit.
set -uo pipefail

# Helm keeps its caches, repository list and registry credentials under $HOME.
# Point every one of them at the test's scratch directory so the test is
# hermetic and works in a sandbox with no writable home.
scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

output="$(@@HELM@@ template @@CHART@@ @@OPTS@@ 2>&1)"
status=$?

if [[ "$status" -eq 0 ]]; then
  echo "FAIL: expected 'helm template' to be rejected, but it rendered successfully." >&2
  echo "----- helm output -----" >&2
  echo "$output" >&2
  exit 1
fi

if ! grep -qF -- '@@EXPECTED@@' <<<"$output"; then
  echo "FAIL: 'helm template' failed as expected, but not for the expected reason." >&2
  echo "expected the output to contain: @@EXPECTED@@" >&2
  echo "----- helm output -----" >&2
  echo "$output" >&2
  exit 1
fi

echo "PASS: 'helm template' was rejected with the expected message."
"""

def _shell_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"

def _helm_template_fail_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart

    script = _RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@EXPECTED@@", ctx.attr.expected_message),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

helm_template_fail_test = rule(
    doc = """Asserts that `helm template` REJECTS a chart for a named reason.

`helm_template_test` from rules_helm proves a chart renders, and its
`template_patterns` prove what it renders. Neither can express the other half of
a chart's contract: the values it must refuse. A `{{ fail }}` guard is the only
mechanism a chart has for rejecting a bad value, and an untested guard is
indistinguishable from an absent one — which is how #770 shipped, an
authorization control that quietly fell back to fail-closed on a typo.

The test passes only when helm exits non-zero AND its combined output contains
`expected_message`, so a chart that starts failing for an unrelated reason (a
broken template, a missing required value) cannot keep the test green.
""",
    implementation = _helm_template_fail_test_impl,
    test = True,
    attrs = {
        "chart": attr.label(
            doc = "The `helm_chart` target to render.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "expected_message": attr.string(
            doc = "Substring that must appear in helm's output. Matched literally.",
            mandatory = True,
        ),
        "opts": attr.string_list(
            doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
        ),
    },
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- helm_template_absent_test ------------------------------------------------

_ABSENT_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_absent_test. Do not edit.
set -uo pipefail

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

output="$(@@HELM@@ template @@CHART@@ @@OPTS@@ 2>&1)"
status=$?
if [[ "$status" -ne 0 ]]; then
  echo "FAIL: 'helm template' did not render (exit $status)." >&2
  echo "$output" >&2
  exit 1
fi

# Control: an empty render would make every absence below vacuous.
if ! grep -qF -- '@@CONTROL@@' <<<"$output"; then
  echo "FAIL: the render does not contain the control string '@@CONTROL@@'; the absence checks cannot be trusted." >&2
  exit 1
fi

rc=0
while IFS= read -r needle; do
  [[ -z "$needle" ]] && continue
  if grep -qF -- "$needle" <<<"$output"; then
    echo "FAIL: the render contains '$needle', which must be absent." >&2
    rc=1
  fi
done <<'__ABSENT__'
@@ABSENT@@
__ABSENT__
[[ "$rc" -eq 0 ]] && echo "PASS: none of the forbidden strings were rendered."
exit "$rc"
"""

def _helm_template_absent_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart
    for s in ctx.attr.absent + [ctx.attr.control]:
        if "\n" in s or s == "__ABSENT__":
            fail("helm_template_absent_test strings must be single lines")

    script = _ABSENT_RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@CONTROL@@", ctx.attr.control),
        ("@@ABSENT@@", "\n".join(ctx.attr.absent)),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

helm_template_absent_test = rule(
    doc = """Asserts that `helm template` renders WITHOUT any of the `absent` strings.

rules_helm's `template_patterns` can only assert presence, so a default-off
component could only be pinned positionally. This renders the chart and fails
if any `absent` string (matched literally) appears in the whole output. The
render must also contain `control` — a string every successful render carries —
so an empty or truncated render cannot pass vacuously.
""",
    implementation = _helm_template_absent_test_impl,
    test = True,
    attrs = {
        "absent": attr.string_list(
            doc = "Strings that must not appear anywhere in the render. Matched literally.",
            mandatory = True,
        ),
        "chart": attr.label(
            doc = "The `helm_chart` target to render.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "control": attr.string(
            doc = "A string the render must contain, proving it rendered something.",
            mandatory = True,
        ),
        "opts": attr.string_list(
            doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
        ),
    },
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- helm_template_match_test -------------------------------------------------

_MATCH_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_match_test. Do not edit.
set -uo pipefail

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

output="$(@@HELM@@ template @@CHART@@ @@OPTS@@ 2>&1)"
status=$?
if [[ "$status" -ne 0 ]]; then
  echo "FAIL: 'helm template' did not render (exit $status)." >&2
  echo "$output" >&2
  exit 1
fi

rc=0
while IFS= read -r pattern; do
  [[ -z "$pattern" ]] && continue
  # Matched by bash itself (POSIX ERE, the C library's regcomp), so the test
  # needs no particular grep: BSD grep has no -P. ERE has no escape for a line
  # break or for whitespace, so the two the patterns use are translated here.
  ere="${pattern//\\\\n/$'\\n'}"
  ere="${ere//\\\\s/[[:space:]]}"
  [[ "$output" =~ $ere ]]
  case $? in
  0) ;;
  1)
    echo "FAIL: the render does not match the pattern:" >&2
    echo "  $pattern" >&2
    rc=1
    ;;
  *)
    echo "FAIL: the pattern is not a valid extended regular expression:" >&2
    echo "  $pattern" >&2
    rc=1
    ;;
  esac
done <<'__PATTERNS__'
@@PATTERNS@@
__PATTERNS__
if [[ "$rc" -ne 0 ]]; then
  echo "----- helm output -----" >&2
  echo "$output" >&2
  exit "$rc"
fi
echo "PASS: the render matches every pattern."
"""

def _helm_template_match_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart
    if not ctx.attr.patterns:
        fail("helm_template_match_test needs at least one pattern")
    for s in ctx.attr.patterns:
        if "\n" in s or s == "__PATTERNS__" or not s:
            fail("helm_template_match_test patterns must be non-empty single lines (write a line break as \\\\n)")

    script = _MATCH_RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@PATTERNS@@", "\n".join(ctx.attr.patterns)),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

helm_template_match_test = rule(
    doc = """Asserts that the WHOLE `helm template` render matches every pattern.

rules_helm's `template_patterns` are matched per template file, and its runner
keeps one document per `# Source:` path: for a template that renders several
documents (`---`), only the one helm prints last is searched, so a pattern for
any earlier document can never match. This rule matches each pattern against
the entire render instead, so a pattern can pin a block in any document and
can span lines. Anchor a pattern on the lines around the block it is about,
since nothing scopes it to one file.

A pattern is a POSIX extended regular expression, matched by bash (`[[ =~ ]]`),
plus two escapes the runner translates: `\\n` (a line break) and `\\s`
(`[[:space:]]`; not usable inside a bracket expression). No Perl syntax: no
`\\d`, no lazy quantifiers, no lookaround.
""",
    implementation = _helm_template_match_test_impl,
    test = True,
    attrs = {
        "chart": attr.label(
            doc = "The `helm_chart` target to render.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "opts": attr.string_list(
            doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
        ),
        "patterns": attr.string_list(
            doc = "Extended regular expressions, each of which must match somewhere in the render. One line each; `\\n` for a line break, `\\s` for whitespace.",
            mandatory = True,
        ),
    },
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- chart_push ---------------------------------------------------------------

# Placeholders are @@-delimited, as above.
_PUSHER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl chart_push. Do not edit.
#
# Pushes ONE packaged chart to @@REPOSITORY@@:<chart version> as the same OCI
# artifact `helm push` writes, with oras (see chart_push's doc for why).

# --- begin runfiles.bash initialization v3 ---
# shellcheck disable=SC1090
set -uo pipefail
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null ||
	source "$0.runfiles/$f" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
	{
		echo >&2 "ERROR: cannot find $f"
		exit 1
	}
f=
set -e
# --- end runfiles.bash initialization v3 ---

die() {
	echo "chart_push @@LABEL@@: $*" >&2
	exit 1
}

# Test / validation seams, never set by publish.yaml: CHART_PUSH_ORAS runs
# another oras (//bazel/helm:chart_push_test records its argv), and
# CHART_PUSH_REPOSITORY pushes somewhere else (a local registry, to prove
# `helm pull` reads the result). Extra arguments go to `oras push` (e.g.
# --plain-http for that local registry).
oras="${CHART_PUSH_ORAS:-$(rlocation '@@ORAS@@')}"
chart="$(rlocation '@@CHART@@')"
config="$(rlocation '@@CONFIG@@')"
meta="$(rlocation '@@META@@')"
repository="${CHART_PUSH_REPOSITORY:-@@REPOSITORY@@}"
for f in "$oras" "$chart" "$config" "$meta"; do
	{ [ -n "$f" ] && [ -r "$f" ]; } || die "missing runfile '${f}'"
done

read -r name version <"$meta" || die "unreadable chart metadata ${meta}"
[ "$name" = '@@NAME@@' ] || die "the package is chart '${name}', but this target pushes chart '@@NAME@@' to ${repository}"
# helm's own rule: an OCI tag cannot hold '+', so SemVer build metadata is
# written with '_' (helm push and helm pull both translate it).
tag="${version//+/_}"
if ! [[ "$tag" =~ ^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$ ]]; then
	die "version '${version}' is not a valid OCI tag -- an unstamped package? Publish with --stamp."
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
# The layer is named the way `helm package` names the archive; oras records the
# file name as the layer's title annotation and wants a relative path.
cp "$chart" "${work}/${name}-${version}.tgz"
cp "$config" "${work}/config.json"
cd "$work"
echo "pushing ${name} ${version} -> ${repository}:${tag}"
"$oras" push "$@" \\
	--annotation "org.opencontainers.image.title=${name}" \\
	--annotation "org.opencontainers.image.version=${version}" \\
	--config "config.json:application/vnd.cncf.helm.config.v1+json" \\
	"${repository}:${tag}" \\
	"${name}-${version}.tgz:application/vnd.cncf.helm.chart.content.v1.tar+gzip"
echo "pushed ${repository}:${tag} (helm pull oci://${repository} --version ${version})"
"""

def _rlocationpath(ctx, f):
    """The runfiles path of `f` for `rlocation` (external repositories included)."""
    if f.short_path.startswith("../"):
        return f.short_path[len("../"):]
    return "{}/{}".format(ctx.workspace_name, f.short_path)

def _chart_push_impl(ctx):
    pkg = ctx.attr.package[HelmPackageInfo]
    oras = ctx.executable._oras

    config = ctx.actions.declare_file(ctx.label.name + ".config.json")
    meta = ctx.actions.declare_file(ctx.label.name + ".meta")
    ctx.actions.run(
        executable = ctx.executable._chartconfig,
        arguments = [
            "-chart",
            pkg.chart.path,
            "-config_out",
            config.path,
            "-meta_out",
            meta.path,
        ],
        inputs = [pkg.chart],
        outputs = [config, meta],
        mnemonic = "HelmChartConfig",
        progress_message = "Deriving the helm OCI config of %{label}",
    )

    script = _PUSHER
    for placeholder, value in [
        ("@@LABEL@@", str(ctx.label)),
        ("@@ORAS@@", _rlocationpath(ctx, oras)),
        ("@@CHART@@", _rlocationpath(ctx, pkg.chart)),
        ("@@CONFIG@@", _rlocationpath(ctx, config)),
        ("@@META@@", _rlocationpath(ctx, meta)),
        ("@@REPOSITORY@@", ctx.attr.repository),
        ("@@NAME@@", ctx.attr.chart_name),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    runfiles = ctx.runfiles(files = [oras, pkg.chart, config, meta])
    runfiles = runfiles.merge(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    return [DefaultInfo(
        executable = runner,
        files = depset([runner, config, meta]),
        runfiles = runfiles,
    )]

chart_push = rule(
    doc = """Pushes a packaged chart to a repository it NAMES, with oras (proposal 040).

`helm push` derives the repository's last path segment from Chart.yaml's
`name:` and nothing else, so it can only publish chart `aether` as
`<base>/aether`. Quay has no nested repositories, and the charts live under a
flat `chart-<name>` prefix (@aether_registry//:registry.bzl): `chart-aether`, and
`chart-prober` / `chart-udsecho`, which would otherwise collide with the prober
and udsecho IMAGE repositories. So this writes exactly the artifact `helm push`
writes -- the packaged .tgz as an
`application/vnd.cncf.helm.chart.content.v1.tar+gzip` layer and Chart.yaml (as
JSON, //bazel/chartconfig) as the `application/vnd.cncf.helm.config.v1+json`
config -- with `oras push <repository>:<chart version>`, and
`helm pull oci://<repository> --version <chart version>` reads it back like any
helm-pushed chart.

The tag is the PACKAGED version (the stamped one: `X.Y.Z-<full sha>` for a
`-{GIT_COMMIT}` chart), so two packagings of one chart publish two tags. A
version that is not a valid OCI tag (an unstamped build) is refused at run
time, never pushed. Registry credentials come from the Docker config, which
`docker login` / docker/login-action writes.

`bazel run --stamp <target> [-- <extra oras push flags>]`.
""",
    implementation = _chart_push_impl,
    executable = True,
    attrs = {
        "chart_name": attr.string(
            doc = "The chart's Chart.yaml `name:`; the push refuses a package that is some other chart.",
            mandatory = True,
        ),
        "package": attr.label(
            doc = "The `helm_chart` / `helm_package` target to push.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "repository": attr.string(
            doc = "Host-qualified repository, no scheme and no tag: chart_registry_url(<chart>).",
            mandatory = True,
        ),
        "_chartconfig": attr.label(
            default = Label("//bazel/chartconfig"),
            executable = True,
            cfg = "exec",
        ),
        "_oras": attr.label(
            default = Label("//bazel/oras:oras_bin"),
            executable = True,
            allow_single_file = True,
            cfg = "target",
        ),
        "_runfiles_lib": attr.label(
            default = Label("@bazel_tools//tools/bash/runfiles"),
        ),
    },
)
