"""Helm chart test rules that rules_helm does not provide."""

load("@rules_helm//helm:defs.bzl", "HelmPackageInfo")

# Placeholders are @@-delimited so nothing in the script collides with bash's
# own ${...} / $(...) syntax.
_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_fail_test. Do not edit.
set -uo pipefail

# Helm keeps its caches, repository list and registry credentials under $HOME.
# Point every one of them at the test's scratch directory so the test is
# hermetic and works in a sandbox with no writable home.
scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

output="$(@@HELM@@ template @@CHART@@ @@OPTS@@ 2>&1)"
status=$?

if [[ "$status" -eq 0 ]]; then
  echo "FAIL: expected 'helm template' to be rejected, but it rendered successfully." >&2
  echo "----- helm output -----" >&2
  echo "$output" >&2
  exit 1
fi

if ! grep -qF -- '@@EXPECTED@@' <<<"$output"; then
  echo "FAIL: 'helm template' failed as expected, but not for the expected reason." >&2
  echo "expected the output to contain: @@EXPECTED@@" >&2
  echo "----- helm output -----" >&2
  echo "$output" >&2
  exit 1
fi

echo "PASS: 'helm template' was rejected with the expected message."
"""

def _shell_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"

def _helm_template_fail_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart

    script = _RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@EXPECTED@@", ctx.attr.expected_message),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

helm_template_fail_test = rule(
    doc = """Asserts that `helm template` REJECTS a chart for a named reason.

`helm_template_test` from rules_helm proves a chart renders, and its
`template_patterns` prove what it renders. Neither can express the other half of
a chart's contract: the values it must refuse. A `{{ fail }}` guard is the only
mechanism a chart has for rejecting a bad value, and an untested guard is
indistinguishable from an absent one — which is how #770 shipped, an
authorization control that quietly fell back to fail-closed on a typo.

The test passes only when helm exits non-zero AND its combined output contains
`expected_message`, so a chart that starts failing for an unrelated reason (a
broken template, a missing required value) cannot keep the test green.
""",
    implementation = _helm_template_fail_test_impl,
    test = True,
    attrs = {
        "chart": attr.label(
            doc = "The `helm_chart` target to render.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "expected_message": attr.string(
            doc = "Substring that must appear in helm's output. Matched literally.",
            mandatory = True,
        ),
        "opts": attr.string_list(
            doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
        ),
    },
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)
