"""Helm rules that rules_helm does not provide: a template-rejection test, a template-absence test, a whole-render and per-document match test, a pod-template version-independence test, a derived-value test, a render-reproducibility test and a named-repository chart push."""

load("@rules_helm//helm:defs.bzl", "HelmPackageInfo")

# Placeholders are @@-delimited so nothing in the script collides with bash's
# own ${...} / $(...) syntax.
_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_fail_test. Do not edit.
set -uo pipefail
# shellcheck source=/dev/null
source @@LIB@@ || exit 1

# Helm keeps its caches, repository list and registry credentials under $HOME.
# Point every one of them at the test's scratch directory so the test is
# hermetic and works in a sandbox with no writable home.
scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

# The render (stdout) and what helm says about it (stderr) are kept apart: only
# the second is ever shown, and a render helm printed before failing is not.
output="$(@@HELM@@ template @@CHART@@ @@OPTS@@ 2>"$scratch/helm.err")"
status=$?
errors="$(cat "$scratch/helm.err")"

if [[ "$status" -eq 0 ]]; then
  # The render itself says nothing about a rejection that did not happen, and
  # it may hold a generated key (#1382): it is not printed.
  echo "FAIL: expected 'helm template' to be rejected, but it rendered successfully ($(grep -c '' <<<"$output") lines, not shown)." >&2
  exit 1
fi

if ! grep -qF -- '@@EXPECTED@@' <<<"$errors"$'\\n'"$output"; then
  echo "FAIL: 'helm template' failed as expected, but not for the expected reason." >&2
  echo "expected the output to contain: @@EXPECTED@@" >&2
  echo "----- what helm said (its stderr) -----" >&2
  show_helm_failure "$errors"
  exit 1
fi

echo "PASS: 'helm template' was rejected with the expected message."
"""

def _shell_quote(s):
    return "'" + s.replace("'", "'\\''") + "'"

# The shell the runners below share: masking the data of Secret documents in
# anything they print, and splitting a render into its documents. Every rule
# that sources it (`source @@LIB@@`) carries this attribute and puts the file in
# its runfiles.
_RENDER_LIB_ATTR = {
    "_render_lib": attr.label(
        default = Label("//bazel/helm:render_lib.sh"),
        allow_single_file = True,
    ),
}

def _helm_template_fail_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart

    script = _RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@LIB@@", _shell_quote(ctx.file._render_lib.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@EXPECTED@@", ctx.attr.expected_message),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            ctx.file._render_lib,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

_FAIL_ATTRS = {
    "chart": attr.label(
        doc = "The `helm_chart` target to render.",
        mandatory = True,
        providers = [HelmPackageInfo],
    ),
    "expected_message": attr.string(
        doc = "Substring that must appear in helm's output. Matched literally.",
        mandatory = True,
    ),
    "opts": attr.string_list(
        doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
    ),
} | _RENDER_LIB_ATTR

helm_template_fail_test = rule(
    doc = """Asserts that `helm template` REJECTS a chart for a named reason.

`helm_template_test` from rules_helm proves a chart renders, and its
`template_patterns` prove what it renders. Neither can express the other half of
a chart's contract: the values it must refuse. A `{{ fail }}` guard is the only
mechanism a chart has for rejecting a bad value, and an untested guard is
indistinguishable from an absent one — which is how #770 shipped, an
authorization control that quietly fell back to fail-closed on a typo.

The test passes only when helm exits non-zero AND its combined output contains
`expected_message`, so a chart that starts failing for an unrelated reason (a
broken template, a missing required value) cannot keep the test green.
""",
    implementation = _helm_template_fail_test_impl,
    test = True,
    attrs = _FAIL_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

helm_template_fail_runner = rule(
    doc = """The runner of `helm_template_fail_test`, as a plain executable instead of a test.

For //bazel/helm:template_rules_test only: what a test rule prints when it
FAILS can only be read from a run that fails, and a target that fails by design
cannot be a test (CI runs every test target it finds, `manual` or not). Same
implementation, same attributes; nothing else should use it.
""",
    implementation = _helm_template_fail_test_impl,
    executable = True,
    attrs = _FAIL_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- helm_template_absent_test ------------------------------------------------

_ABSENT_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_absent_test. Do not edit.
set -uo pipefail
# shellcheck source=/dev/null
source @@LIB@@ || exit 1

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

# The render (stdout) and what helm says about it (stderr) are kept apart: only
# the second is ever shown, and a render helm printed before failing is not.
output="$(@@HELM@@ template @@CHART@@ @@OPTS@@ 2>"$scratch/helm.err")"
status=$?
errors="$(cat "$scratch/helm.err")"
if [[ "$status" -ne 0 ]]; then
  echo "FAIL: 'helm template' did not render (exit $status)." >&2
  show_helm_failure "$errors"
  exit 1
fi

# Control: an empty render would make every absence below vacuous.
if ! grep -qF -- '@@CONTROL@@' <<<"$output"; then
  echo "FAIL: the render does not contain the control string '@@CONTROL@@'; the absence checks cannot be trusted." >&2
  exit 1
fi

rc=0
while IFS= read -r needle; do
  [[ -z "$needle" ]] && continue
  if grep -qF -- "$needle" <<<"$output"; then
    echo "FAIL: the render contains '$needle', which must be absent." >&2
    rc=1
  fi
done <<'__ABSENT__'
@@ABSENT@@
__ABSENT__
[[ "$rc" -eq 0 ]] && echo "PASS: none of the forbidden strings were rendered."
exit "$rc"
"""

def _helm_template_absent_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart
    for s in ctx.attr.absent + [ctx.attr.control]:
        if "\n" in s or s == "__ABSENT__":
            fail("helm_template_absent_test strings must be single lines")

    script = _ABSENT_RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@LIB@@", _shell_quote(ctx.file._render_lib.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@CONTROL@@", ctx.attr.control),
        ("@@ABSENT@@", "\n".join(ctx.attr.absent)),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            ctx.file._render_lib,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

_ABSENT_ATTRS = {
    "absent": attr.string_list(
        doc = "Strings that must not appear anywhere in the render. Matched literally.",
        mandatory = True,
    ),
    "chart": attr.label(
        doc = "The `helm_chart` target to render.",
        mandatory = True,
        providers = [HelmPackageInfo],
    ),
    "control": attr.string(
        doc = "A string the render must contain, proving it rendered something.",
        mandatory = True,
    ),
    "opts": attr.string_list(
        doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
    ),
} | _RENDER_LIB_ATTR

helm_template_absent_test = rule(
    doc = """Asserts that `helm template` renders WITHOUT any of the `absent` strings.

rules_helm's `template_patterns` can only assert presence, so a default-off
component could only be pinned positionally. This renders the chart and fails
if any `absent` string (matched literally) appears in the whole output. The
render must also contain `control` — a string every successful render carries —
so an empty or truncated render cannot pass vacuously.
""",
    implementation = _helm_template_absent_test_impl,
    test = True,
    attrs = _ABSENT_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

helm_template_absent_runner = rule(
    doc = """The runner of `helm_template_absent_test`, as a plain executable instead of a test.

For //bazel/helm:template_rules_test only: what a test rule prints when it
FAILS can only be read from a run that fails, and a target that fails by design
cannot be a test (CI runs every test target it finds, `manual` or not). Same
implementation, same attributes; nothing else should use it.
""",
    implementation = _helm_template_absent_test_impl,
    executable = True,
    attrs = _ABSENT_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- helm_template_match_test -------------------------------------------------

_MATCH_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_match_test. Do not edit.
set -uo pipefail
# shellcheck source=/dev/null
source @@LIB@@ || exit 1

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

# The render (stdout) and what helm says about it (stderr) are kept apart: only
# the second is ever shown, and a render helm printed before failing is not.
output="$(@@HELM@@ template @@CHART@@ @@OPTS@@ 2>"$scratch/helm.err")"
status=$?
errors="$(cat "$scratch/helm.err")"
if [[ "$status" -ne 0 ]]; then
  echo "FAIL: 'helm template' did not render (exit $status)." >&2
  show_helm_failure "$errors"
  exit 1
fi

# The render, as one file per document and as a whole, each with a copy in
# which Secret data is masked. A pattern is matched against the text as
# rendered; anything this script PRINTS comes from a masked copy (#1382).
work="$scratch/match"
printf '%s\\n' "$output" >"$scratch/render.yaml"
split_documents "$scratch/render.yaml" "$work"

rc=0
matched=0
scope="the whole render"
scope_text="$output"
scope_masked="$work/render.masked"
scope_ok=1

select_document() { # <Kind>/<name>: the document the next patterns are for
  local found count n source position
  found="$(_awk -F'|' -v want="$1" '$3 == want' "$work/index")"
  count="$(grep -c . <<<"$found")"
  if [[ "$count" -ne 1 ]]; then
    if [[ "$count" -eq 0 ]]; then
      echo "FAIL: the render has no document $1 (a document is found by its 'kind:' line and its 'metadata:' / '  name:' lines, so one written as a flow mapping or JSON cannot be named; use patterns for it). It has:" >&2
    else
      echo "FAIL: the render has $count documents $1, so the patterns for it cannot say which they mean. It has:" >&2
    fi
    list_documents "$work" >&2
    scope_ok=0
    rc=1
    return
  fi
  IFS='|' read -r n source _ position <<<"$found"
  scope="$1 ($source, document $position)"
  scope_text="$(cat "$work/doc.$n")"
  scope_masked="$work/doc.$n.masked"
  scope_ok=1
}

check_pattern() { # <pattern>
  # A document that is not there has already failed the test, once.
  [[ "$scope_ok" -eq 1 ]] || return 0
  # Matched by bash itself (POSIX ERE, the C library's regcomp), so the test
  # needs no particular grep: BSD grep has no -P.
  translate_pattern "$1"
  [[ "$scope_text" =~ $ere ]]
  case $? in
  0) matched=$((matched + 1)) ;;
  1)
    echo "FAIL: $scope does not match the pattern:" >&2
    echo "  $1" >&2
    show_excerpt "$1" "$scope_text" "$scope_masked" "$scope"
    rc=1
    ;;
  *)
    echo "FAIL: the pattern is not a valid extended regular expression:" >&2
    echo "  $1" >&2
    rc=1
    ;;
  esac
}

# `@<Kind>/<name>` selects a document, `=<pattern>` is a pattern for the
# current selection (the whole render until a document is selected).
while IFS= read -r line; do
  case "$line" in
  @*) select_document "${line:1}" ;;
  =*) check_pattern "${line:1}" ;;
  esac
done <<'__SPEC__'
@@SPEC@@
__SPEC__
if [[ "$rc" -ne 0 ]]; then
  echo "(excerpts are from a masked copy of the render: a document that is not plainly a kind other than Secret shows its apiVersion, kind, type, name and namespace only; the whole render is never printed)" >&2
  exit "$rc"
fi
echo "PASS: all $matched patterns match."
"""

def _helm_template_match_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart
    if not ctx.attr.patterns and not ctx.attr.document_patterns:
        fail("helm_template_match_test needs at least one pattern (patterns or document_patterns)")

    # One line each: `=<pattern>` for the whole render first, then per document
    # `@<Kind>/<name>` followed by its patterns.
    spec = []
    for document, patterns in [("", ctx.attr.patterns)] + list(ctx.attr.document_patterns.items()):
        if document:
            parts = document.split("/")
            if "\n" in document or "|" in document or len(parts) != 2 or not parts[0] or not parts[1]:
                fail("helm_template_match_test document_patterns keys are `<Kind>/<name>`, got %r" % document)
            if not patterns:
                fail("helm_template_match_test document %r has no pattern" % document)
            spec.append("@" + document)
        for s in patterns:
            if "\n" in s or s == "__SPEC__" or not s:
                fail("helm_template_match_test patterns must be non-empty single lines (write a line break as \\\\n)")
            spec.append("=" + s)

    script = _MATCH_RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@LIB@@", _shell_quote(ctx.file._render_lib.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@SPEC@@", "\n".join(spec)),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            ctx.file._render_lib,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

_MATCH_ATTRS = {
    "chart": attr.label(
        doc = "The `helm_chart` target to render.",
        mandatory = True,
        providers = [HelmPackageInfo],
    ),
    "document_patterns": attr.string_list_dict(
        doc = "`<Kind>/<name>` of one rendered document -> extended regular expressions, each of which must match inside that document.",
    ),
    "opts": attr.string_list(
        doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
    ),
    "patterns": attr.string_list(
        doc = "Extended regular expressions, each of which must match somewhere in the render. One line each; `\\n` for a line break, `\\s` for whitespace.",
    ),
} | _RENDER_LIB_ATTR

helm_template_match_test = rule(
    doc = """Asserts that a `helm template` render matches every pattern: the whole render, or one named document of it.

rules_helm's `template_patterns` are matched per template file, and its runner
keeps one document per `# Source:` path: for a template that renders several
documents (`---`), only the one helm prints last is searched, so a pattern for
any earlier document can never match (#1371). Helm prints a release's objects
sorted by kind, so "last" is not the last one in the template file either.

`patterns` are matched against the entire render: a pattern can pin a block in
any document and can span lines, and nothing scopes it, so anchor it on the
lines around the block it is about.

`document_patterns` maps `<Kind>/<name>` to patterns that must each match
inside that one document, whichever template file it comes from and wherever
in that file it is. Only a document written in block style can be named: its
`kind:` at the start of a line, and `metadata:` followed by a `  name:` line.
A document written as a flow mapping or as JSON (`{kind: ..., metadata: ...}`)
is not indexed; use `patterns` for it. The name is the rendered `metadata.name`; the runner
renders without a release name, so helm's default (`release-name`) is the
prefix a chart that uses `.Release.Name` gives it. The test fails when the
render has no such document, or more than one (the same kind and name in two
namespaces): a pattern that cannot say which document it is about is not
matched against either.

A pattern is a POSIX extended regular expression, matched by bash (`[[ =~ ]]`),
plus three escapes the runner translates: `\\n` (a line break), `\\s`
(`[[:space:]]`) and `\\S` (`[^[:space:]]`); the last two are not usable inside
a bracket expression. No Perl syntax: no `\\d`, no `(?s)`, no lazy
quantifiers, no lookaround.

On a mismatch the test prints the pattern, what it searched (the document's
kind and name, its template file, and which of that file's documents it is in
the order helm prints them), and at most sixteen lines from the place where
the longest leading part of the pattern still matches, with the first line the
pattern did not expect marked. It never prints
the whole render, and what it prints comes from a masked copy (#1382): the
aether chart generates a webhook private key at render time. The patterns
themselves are matched against the render as it is, so a test can still assert
on a Secret.

The mask fails closed. It does not try to recognise a Secret. A document is
printed as it is only when it is plainly something else: exactly one top-level
kind line, of the plain form `kind: <Word>` (optionally quoted, optionally
followed by a comment), whose word is neither `Secret` nor `List`, in a
document that is not written in flow style, has no top-level explicit or merge
key, and holds no `kind: Secret` anywhere else. In a document that might be a
Secret, only these lines are ever printed, and only as simple `key: scalar`
lines: the `# Source:` comment, `apiVersion:`, `kind:`, `type:`, `metadata:`
and the `name:` and `namespace:` directly under it. Every other line is
`<masked>`, so it does not matter how such a document spells its data. A
ConfigMap with a plain kind line stays readable in an excerpt.
""",
    implementation = _helm_template_match_test_impl,
    test = True,
    attrs = _MATCH_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

helm_template_match_runner = rule(
    doc = """The runner of `helm_template_match_test`, as a plain executable instead of a test.

For //bazel/helm:template_rules_test only: what a test rule prints when it
FAILS can only be read from a run that fails, and a target that fails by design
cannot be a test (CI runs every test target it finds, `manual` or not). Same
implementation, same attributes; nothing else should use it.
""",
    implementation = _helm_template_match_test_impl,
    executable = True,
    attrs = _MATCH_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- helm_pod_template_version_test -------------------------------------------

_VERSION_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_pod_template_version_test. Do not edit.
set -uo pipefail
# shellcheck source=/dev/null
source @@LIB@@ || exit 1

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

# Two copies of the packaged chart: `a` as packaged, `b` with another chart
# version AND another appVersion. Nothing else differs between them.
other_version='999.0.0-otherversion'
other_app_version='other-app-version'
work="$scratch/version"
rm -rf "$work"
mkdir -p "$work/a" "$work/b"
tar -xzf @@CHART@@ -C "$work/a" || fail "cannot unpack the chart"
tar -xzf @@CHART@@ -C "$work/b" || fail "cannot unpack the chart"
chart_a="$(find "$work/a" -mindepth 1 -maxdepth 1 -type d)"
chart_b="$(find "$work/b" -mindepth 1 -maxdepth 1 -type d)"
[[ -f "$chart_a/Chart.yaml" && -f "$chart_b/Chart.yaml" ]] || fail "the package does not hold exactly one chart directory"
name="$(sed -n 's/^name:[[:space:]]*//p' "$chart_a/Chart.yaml" | tr -d "\\"'")"
version="$(sed -n 's/^version:[[:space:]]*//p' "$chart_a/Chart.yaml" | tr -d "\\"'")"
[[ -n "$name" && -n "$version" ]] || fail "cannot read name/version from the packaged Chart.yaml"
[[ "$version" != "$other_version" ]] || fail "the chart already has the version this test substitutes"
grep -vE '^(version|appVersion):' "$chart_a/Chart.yaml" >"$chart_b/Chart.yaml"
printf 'version: %s\\nappVersion: %s\\n' "$other_version" "$other_app_version" >>"$chart_b/Chart.yaml"

render() { # <chart dir> <out>
  if ! @@HELM@@ template release "$1" @@OPTS@@ >"$2" 2>"$2.err"; then
    show_helm_failure "$(cat "$2.err")"
    fail "'helm template' did not render $1"
  fi
}
render "$chart_a" "$work/a.yaml"
render "$chart_b" "$work/b.yaml"

# Control: the substituted version must reach the render, or "the pod templates
# are identical" below would be true of two identical charts.
grep -qF -- "helm.sh/chart: ${name}-${other_version}" "$work/b.yaml" ||
  fail "the second render does not carry helm.sh/chart: ${name}-${other_version}; the version substitution did not take effect"
if grep -qF -- "$other_version" "$work/a.yaml"; then
  fail "the first render carries the substituted version"
fi

# mode=pods:   every workload's pod template (`spec.template` up to the next
#              key at that depth), under a `### <Kind>/<name>` header.
# mode=labels: `<Kind>/<name> <helm.sh/chart value>` for the workload OBJECT's
#              own metadata (the lines before its `spec:`), `-` when absent.
extract() { # <mode> <render>
  awk -v mode="$1" '
    function end_doc() {
      if (workload && mode == "labels") print kind "/" name, (chart == "" ? "-" : chart)
      kind = ""; name = ""; chart = ""; workload = 0; in_meta = 0; in_tpl = 0
    }
    /^---[ \\t]*$/ { end_doc(); next }
    /^kind:/ {
      kind = $2
      workload = (kind ~ /^(DaemonSet|Deployment|StatefulSet|ReplicaSet|Job)$/)
      in_meta = 1
      next
    }
    /^spec:/ { in_meta = 0 }
    in_meta && name == "" && /^  name:/ { name = $2 }
    in_meta && /^    helm\\.sh\\/chart:/ { chart = $2 }
    workload && /^  template:[ \\t]*$/ {
      in_tpl = 1
      if (mode == "pods") print "### " kind "/" name
      next
    }
    in_tpl && /^(  )?[A-Za-z]/ { in_tpl = 0 }
    in_tpl && mode == "pods" { print }
    END { end_doc() }
  ' "$2"
}

rc=0
for r in a b; do
  extract pods "$work/$r.yaml" >"$work/$r.pods"
  extract labels "$work/$r.yaml" >"$work/$r.labels"
done

# Every workload document must have yielded exactly one pod template, and there
# must be as many as the test says the chart renders: a workload the extraction
# cannot see (or a render that lost one) fails here instead of passing unseen.
# A CronJob keeps its pod template under spec.jobTemplate.spec.template, which
# the extraction above does not read. Refuse it by name rather than report a
# count that does not add up.
# Both renders are checked: a workload a template emits only at the other
# version must not slip past the comparison.
for r in a b; do
  if grep -qE '^kind: CronJob[[:space:]]*$' "$work/$r.yaml"; then
    fail "render $r contains a CronJob, whose pod template (spec.jobTemplate.spec.template) this test does not extract; teach extract() about it first"
  fi
  workloads="$(grep -cE '^kind: (DaemonSet|Deployment|StatefulSet|ReplicaSet|Job)[[:space:]]*$' "$work/$r.yaml")"
  templates="$(grep -c '^### ' "$work/$r.pods")"
  if [[ "$workloads" -ne @@WORKLOADS@@ || "$templates" -ne @@WORKLOADS@@ ]]; then
    echo "FAIL: expected @@WORKLOADS@@ workloads; render $r has $workloads workload objects and $templates pod templates were extracted." >&2
    rc=1
  fi
done

# 1. The pod templates do not depend on the chart version or the appVersion.
if cmp -s "$work/a.pods" "$work/b.pods"; then
  echo "PASS: the $templates pod templates are byte-identical at chart versions $version and $other_version."
else
  echo "FAIL: a pod template changes with the chart version alone, so every release rolls that workload's pods:" >&2
  diff "$work/a.pods" "$work/b.pods" | awk '/^[<>]/ && n++ < 40' >&2
  echo "(workloads affected:" >&2
  diff --unchanged-line-format= --old-line-format= --new-line-format='%dn ' "$work/a.pods" "$work/b.pods" >"$work/changed.lines"
  awk 'NR == FNR { for (i = 1; i <= NF; i++) want[$i] = 1; next } /^### / { cur = $2 } (FNR in want) && !(cur in seen) { seen[cur] = 1; printf "  %s\\n", cur }' "$work/changed.lines" "$work/b.pods" >&2
  echo ")" >&2
  rc=1
fi

# 2. The workload objects themselves still say which chart rendered them.
for r in a b; do
  want="${name}-${version}"
  [[ "$r" == b ]] && want="${name}-${other_version}"
  while read -r workload chart; do
    if [[ "$chart" != "$want" ]]; then
      echo "FAIL: $workload carries helm.sh/chart '$chart' on its own metadata, want '$want'." >&2
      rc=1
    fi
  done <"$work/$r.labels"
  [[ "$(wc -l <"$work/$r.labels")" -eq "$workloads" ]] || {
    echo "FAIL: read the labels of $(wc -l <"$work/$r.labels") workload objects, want $workloads." >&2
    rc=1
  }
done
[[ "$rc" -eq 0 ]] && echo "PASS: all $workloads workload objects carry helm.sh/chart: <name>-<version> on their own metadata."
exit "$rc"
"""

def _helm_pod_template_version_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart

    script = _VERSION_RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@LIB@@", _shell_quote(ctx.file._render_lib.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@WORKLOADS@@", str(ctx.attr.workloads)),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            ctx.file._render_lib,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

_POD_TEMPLATE_VERSION_ATTRS = {
    "chart": attr.label(
        doc = "The `helm_chart` target to render.",
        mandatory = True,
        providers = [HelmPackageInfo],
    ),
    "opts": attr.string_list(
        doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
    ),
    "workloads": attr.int(
        doc = "The number of workload objects (DaemonSet, Deployment, ...) this render contains.",
        mandatory = True,
    ),
} | _RENDER_LIB_ATTR

helm_pod_template_version_test = rule(
    doc = """Asserts that no pod template depends on the chart's version or appVersion (#1363).

A pod template that carries the chart version (a `helm.sh/chart` or
`app.kubernetes.io/version` label, the version in an env var or an argument)
changes with every release, so every release rolls that workload's pods whether
or not anything about them changed. `helm template` cannot override the version
of a chart it is given, so this unpacks the packaged chart twice, rewrites
`version:` and `appVersion:` in one copy's Chart.yaml, renders both with the
same `opts`, and compares every workload's `spec.template` byte for byte.

It also asserts the other half: each workload OBJECT still carries
`helm.sh/chart: <name>-<version>` on its own metadata, at both versions, so
the label was moved off the pods and not dropped.

`workloads` is how many workload objects (DaemonSet, Deployment, StatefulSet,
ReplicaSet, Job) the render must contain; the test fails when the render or
the extraction disagrees. A CronJob nests its pod template one level deeper
(`spec.jobTemplate.spec.template`); the test refuses a render that contains one
instead of passing it unseen.
""",
    implementation = _helm_pod_template_version_test_impl,
    test = True,
    attrs = _POD_TEMPLATE_VERSION_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

helm_pod_template_version_runner = rule(
    doc = """The runner of `helm_pod_template_version_test`, as a plain executable instead of a test.

For //bazel/helm:template_rules_test only (see `helm_template_fail_runner`).
""",
    implementation = _helm_pod_template_version_test_impl,
    executable = True,
    attrs = _POD_TEMPLATE_VERSION_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- helm_template_value_changes_test -----------------------------------------

_CHANGES_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_value_changes_test. Do not edit.
set -uo pipefail
# shellcheck source=/dev/null
source @@LIB@@ || exit 1

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

value() { # <label> <helm args...>: the one rendered line that holds the key
  local label="$1" out lines count
  shift
  out="$(@@HELM@@ template release @@CHART@@ "$@" 2>"$scratch/helm.err")" || {
    show_helm_failure "$(cat "$scratch/helm.err")"
    fail "'helm template' did not render ($label)"
  }
  lines="$(grep -F -- '@@KEY@@' <<<"$out" | grep -vE '^[[:space:]]*#')"
  # Never the lines themselves: they are rendered values, and a key can name a
  # Secret's (#1382).
  count="$(grep -c . <<<"$lines")"
  [[ "$count" -eq 1 ]] || fail "expected exactly one rendered, non-comment line holding '@@KEY@@' ($label), found $count (the lines are not shown)"
  printf '%s\\n' "$lines"
}

a="$(value "opts" @@OPTS@@)" || exit 1
b="$(value "opts + changed_opts" @@OPTS@@ @@CHANGED_OPTS@@)" || exit 1
c="$(value "opts, again" @@OPTS@@)" || exit 1
[[ "$a" == "$c" ]] || fail "'@@KEY@@' differs between two renders of the same values: it is not a function of them"
[[ "$a" != "$b" ]] || fail "the line holding '@@KEY@@' is the same with and without the changed values (the line is not shown)"
echo "PASS: '@@KEY@@' follows the changed values and is stable for unchanged ones."
"""

def _helm_template_value_changes_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart
    if "\n" in ctx.attr.key or "'" in ctx.attr.key:
        fail("helm_template_value_changes_test key must be a single line without single quotes")

    script = _CHANGES_RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@LIB@@", _shell_quote(ctx.file._render_lib.short_path)),
        ("@@CHANGED_OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.changed_opts])),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@KEY@@", ctx.attr.key),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            ctx.file._render_lib,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

_VALUE_CHANGES_ATTRS = {
    "changed_opts": attr.string_list(
        doc = "Extra `helm template` arguments that must change the line.",
        mandatory = True,
    ),
    "chart": attr.label(
        doc = "The `helm_chart` target to render.",
        mandatory = True,
        providers = [HelmPackageInfo],
    ),
    "key": attr.string(
        doc = "A literal string that identifies exactly one rendered, non-comment line.",
        mandatory = True,
    ),
    "opts": attr.string_list(
        doc = "`helm template` arguments common to both renders.",
    ),
} | _RENDER_LIB_ATTR

helm_template_value_changes_test = rule(
    doc = """Asserts that one rendered line changes when some values change, and only then.

For a derived value whose whole purpose is to follow its input: a config
checksum annotation that must roll a pod when the config changes. Pinning the
checksum would have to be updated with every config change, and asserting only
its shape (`[0-9a-f]{64}`) would pass for a constant. This renders with `opts`,
with `opts + changed_opts`, and with `opts` again, and requires the single
non-comment line containing `key` to differ in the second render and to be
identical in the first and third.
""",
    implementation = _helm_template_value_changes_test_impl,
    test = True,
    attrs = _VALUE_CHANGES_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

helm_template_value_changes_runner = rule(
    doc = """The runner of `helm_template_value_changes_test`, as a plain executable instead of a test.

For //bazel/helm:template_rules_test only (see `helm_template_fail_runner`).
""",
    implementation = _helm_template_value_changes_test_impl,
    executable = True,
    attrs = _VALUE_CHANGES_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- helm_template_reproducible_test ------------------------------------------

_REPRODUCIBLE_RUNNER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl helm_template_reproducible_test. Do not edit.
set -uo pipefail
# shellcheck source=/dev/null
source @@LIB@@ || exit 1

scratch="${TEST_TMPDIR:-$(mktemp -d)}/helm"
mkdir -p "$scratch"
export HELM_CACHE_HOME="$scratch/cache"
export HELM_CONFIG_HOME="$scratch/config"
export HELM_DATA_HOME="$scratch/data"
export HELM_REPOSITORY_CACHE="$scratch/repository_cache"
export HELM_REPOSITORY_CONFIG="$scratch/repositories.yaml"
export HELM_REGISTRY_CONFIG="$scratch/registry.json"
export HELM_PLUGINS="@@HELM_PLUGINS@@"

for r in 1 2; do
  if ! @@HELM@@ template release @@CHART@@ @@OPTS@@ >"$scratch/render.$r" 2>"$scratch/render.$r.err"; then
    show_helm_failure "$(cat "$scratch/render.$r.err")"
    echo "FAIL: 'helm template' did not render." >&2
    exit 1
  fi
  [[ -s "$scratch/render.$r" ]] || { echo "FAIL: the render is empty." >&2; exit 1; }
  # The documented recipe: everything after the key of a masked line is dropped.
  sed -E @@MASK@@ "$scratch/render.$r" >"$scratch/masked.$r"
done

rc=0
masked="$(grep -c '<masked>$' "$scratch/masked.1")"
if [[ "$masked" -ne @@MASKED_LINES@@ ]]; then
  echo "FAIL: the mask hid $masked lines, want @@MASKED_LINES@@: the set of values generated at render time changed." >&2
  grep -n '<masked>$' "$scratch/masked.1" >&2
  rc=1
fi
if cmp -s "$scratch/masked.1" "$scratch/masked.2"; then
  echo "PASS: two renders are byte-identical ($masked masked lines)."
else
  echo "FAIL: two renders of the same chart and values differ outside the masked lines:" >&2
  # Never the differing text: a value generated at render time may be a private
  # key, and a test log is not the place for one, however short-lived. A line
  # that starts with a plain YAML key is reported by that key; any other line
  # (a list item, a line of a block scalar) only as a line number.
  diff "$scratch/masked.1" "$scratch/masked.2" | awk '
    /^[0-9]+(,[0-9]+)?[acd][0-9]+(,[0-9]+)?$/ { where = $0; next }
    /^< / {
      line = substr($0, 3)
      if (match(line, /^[[:space:]]*[A-Za-z0-9_.-]+:/)) {
        key = substr(line, RSTART, RLENGTH)
        gsub(/^[[:space:]]+/, "", key)
        print "  first render, at " where ": the value of " key
      } else {
        print "  first render, at " where ": a line with no key (not shown)"
      }
    }' | sort | uniq -c | head -n 20 >&2
  rc=1
fi
exit "$rc"
"""

def _helm_template_reproducible_test_impl(ctx):
    toolchain = ctx.toolchains[Label("@rules_helm//helm:toolchain_type")]
    chart = ctx.attr.chart[HelmPackageInfo].chart
    for key in ctx.attr.masked_keys:
        if not key.replace(".", "").replace("-", "").replace("_", "").isalnum():
            fail("helm_template_reproducible_test masked_keys must be plain YAML keys, got %r" % key)

    # `    ca.crt: LS0t...` -> `    ca.crt: <masked>`. With no key the
    # expression matches nothing, so the render is compared as it is.
    keys = "|".join([key.replace(".", "\\.") for key in ctx.attr.masked_keys]) or "$^"
    mask = "s/^([[:space:]]*(" + keys + "):).*$/\\1 <masked>/"

    script = _REPRODUCIBLE_RUNNER
    for placeholder, value in [
        ("@@HELM_PLUGINS@@", toolchain.helm_plugins.short_path),
        ("@@HELM@@", _shell_quote(toolchain.helm.short_path)),
        ("@@CHART@@", _shell_quote(chart.short_path)),
        ("@@LIB@@", _shell_quote(ctx.file._render_lib.short_path)),
        ("@@OPTS@@", " ".join([_shell_quote(opt) for opt in ctx.attr.opts])),
        ("@@MASKED_LINES@@", str(ctx.attr.masked_lines)),
        ("@@MASK@@", _shell_quote(mask)),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    return [DefaultInfo(
        executable = runner,
        runfiles = ctx.runfiles(files = [
            chart,
            ctx.file._render_lib,
            toolchain.helm,
            toolchain.helm_plugins,
        ]),
    )]

_TEMPLATE_REPRODUCIBLE_ATTRS = {
    "chart": attr.label(
        doc = "The `helm_chart` target to render.",
        mandatory = True,
        providers = [HelmPackageInfo],
    ),
    "masked_keys": attr.string_list(
        doc = "YAML keys whose values are generated at render time (e.g. `tls.crt`, `caBundle`).",
    ),
    "masked_lines": attr.int(
        doc = "The number of lines `masked_keys` must hide in one render.",
        default = 0,
    ),
    "opts": attr.string_list(
        doc = "Additional arguments to pass to `helm template` (e.g. `--set` pairs).",
    ),
} | _RENDER_LIB_ATTR

helm_template_reproducible_test = rule(
    doc = """Asserts that two `helm template` renders of one chart and one set of values are byte-identical (#1364).

A chart that generates something at render time (a certificate, a random
password, a timestamp) cannot be diffed: every before/after comparison of
rendered manifests shows a change that is not one. This renders twice and
compares.

`masked_keys` names the YAML keys whose values are known to be generated at
render time; their values are replaced before the comparison, which is the
recipe the runbook gives operators. `masked_lines` is how many lines that must
hide, so the test also fails when the set of generated values grows or shrinks
without the documentation following. With no `masked_keys` the whole render must
be identical.
""",
    implementation = _helm_template_reproducible_test_impl,
    test = True,
    attrs = _TEMPLATE_REPRODUCIBLE_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

helm_template_reproducible_runner = rule(
    doc = """The runner of `helm_template_reproducible_test`, as a plain executable instead of a test.

For //bazel/helm:template_rules_test only (see `helm_template_fail_runner`).
""",
    implementation = _helm_template_reproducible_test_impl,
    executable = True,
    attrs = _TEMPLATE_REPRODUCIBLE_ATTRS,
    toolchains = [
        str(Label("@rules_helm//helm:toolchain_type")),
    ],
)

# --- chart_push ---------------------------------------------------------------

# Placeholders are @@-delimited, as above.
_PUSHER = """\
#!/usr/bin/env bash
# Generated by //bazel/helm:defs.bzl chart_push. Do not edit.
#
# Pushes ONE packaged chart to @@REPOSITORY@@:<chart version> as the same OCI
# artifact `helm push` writes, with oras (see chart_push's doc for why).

# --- begin runfiles.bash initialization v3 ---
# shellcheck disable=SC1090
set -uo pipefail
set +e
f=bazel_tools/tools/bash/runfiles/runfiles.bash
source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null ||
	source "$0.runfiles/$f" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
	source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null ||
	{
		echo >&2 "ERROR: cannot find $f"
		exit 1
	}
f=
set -e
# --- end runfiles.bash initialization v3 ---

die() {
	echo "chart_push @@LABEL@@: $*" >&2
	exit 1
}

# Test / validation seams, never set by publish.yaml: CHART_PUSH_ORAS runs
# another oras (//bazel/helm:chart_push_test records its argv), and
# CHART_PUSH_REPOSITORY pushes somewhere else (a local registry, to prove
# `helm pull` reads the result). Extra arguments go to `oras push` (e.g.
# --plain-http for that local registry).
oras="${CHART_PUSH_ORAS:-$(rlocation '@@ORAS@@')}"
chart="$(rlocation '@@CHART@@')"
config="$(rlocation '@@CONFIG@@')"
meta="$(rlocation '@@META@@')"
repository="${CHART_PUSH_REPOSITORY:-@@REPOSITORY@@}"
for f in "$oras" "$chart" "$config" "$meta"; do
	{ [ -n "$f" ] && [ -r "$f" ]; } || die "missing runfile '${f}'"
done

read -r name version <"$meta" || die "unreadable chart metadata ${meta}"
[ "$name" = '@@NAME@@' ] || die "the package is chart '${name}', but this target pushes chart '@@NAME@@' to ${repository}"
# helm's own rule: an OCI tag cannot hold '+', so SemVer build metadata is
# written with '_' (helm push and helm pull both translate it).
tag="${version//+/_}"
if ! [[ "$tag" =~ ^[A-Za-z0-9_][A-Za-z0-9._-]{0,127}$ ]]; then
	die "version '${version}' is not a valid OCI tag -- an unstamped package? Publish with --stamp."
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
# The layer is named the way `helm package` names the archive; oras records the
# file name as the layer's title annotation and wants a relative path.
cp "$chart" "${work}/${name}-${version}.tgz"
cp "$config" "${work}/config.json"
cd "$work"
echo "pushing ${name} ${version} -> ${repository}:${tag}"
"$oras" push "$@" \\
	--annotation "org.opencontainers.image.title=${name}" \\
	--annotation "org.opencontainers.image.version=${version}" \\
	--config "config.json:application/vnd.cncf.helm.config.v1+json" \\
	"${repository}:${tag}" \\
	"${name}-${version}.tgz:application/vnd.cncf.helm.chart.content.v1.tar+gzip"
echo "pushed ${repository}:${tag} (helm pull oci://${repository} --version ${version})"
"""

def _rlocationpath(ctx, f):
    """The runfiles path of `f` for `rlocation` (external repositories included)."""
    if f.short_path.startswith("../"):
        return f.short_path[len("../"):]
    return "{}/{}".format(ctx.workspace_name, f.short_path)

def _chart_push_impl(ctx):
    pkg = ctx.attr.package[HelmPackageInfo]
    oras = ctx.executable._oras

    config = ctx.actions.declare_file(ctx.label.name + ".config.json")
    meta = ctx.actions.declare_file(ctx.label.name + ".meta")
    ctx.actions.run(
        executable = ctx.executable._chartconfig,
        arguments = [
            "-chart",
            pkg.chart.path,
            "-config_out",
            config.path,
            "-meta_out",
            meta.path,
        ],
        inputs = [pkg.chart],
        outputs = [config, meta],
        mnemonic = "HelmChartConfig",
        progress_message = "Deriving the helm OCI config of %{label}",
    )

    script = _PUSHER
    for placeholder, value in [
        ("@@LABEL@@", str(ctx.label)),
        ("@@ORAS@@", _rlocationpath(ctx, oras)),
        ("@@CHART@@", _rlocationpath(ctx, pkg.chart)),
        ("@@CONFIG@@", _rlocationpath(ctx, config)),
        ("@@META@@", _rlocationpath(ctx, meta)),
        ("@@REPOSITORY@@", ctx.attr.repository),
        ("@@NAME@@", ctx.attr.chart_name),
    ]:
        script = script.replace(placeholder, value)

    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = script, is_executable = True)

    runfiles = ctx.runfiles(files = [oras, pkg.chart, config, meta])
    runfiles = runfiles.merge(ctx.attr._runfiles_lib[DefaultInfo].default_runfiles)
    return [DefaultInfo(
        executable = runner,
        files = depset([runner, config, meta]),
        runfiles = runfiles,
    )]

chart_push = rule(
    doc = """Pushes a packaged chart to a repository it NAMES, with oras (proposal 040).

`helm push` derives the repository's last path segment from Chart.yaml's
`name:` and nothing else, so it can only publish chart `aether` as
`<base>/aether`. Quay has no nested repositories, and the charts live under a
flat `chart-<name>` prefix (@aether_registry//:registry.bzl): `chart-aether`, and
`chart-prober` / `chart-udsecho`, which would otherwise collide with the prober
and udsecho IMAGE repositories. So this writes exactly the artifact `helm push`
writes -- the packaged .tgz as an
`application/vnd.cncf.helm.chart.content.v1.tar+gzip` layer and Chart.yaml (as
JSON, //bazel/chartconfig) as the `application/vnd.cncf.helm.config.v1+json`
config -- with `oras push <repository>:<chart version>`, and
`helm pull oci://<repository> --version <chart version>` reads it back like any
helm-pushed chart.

The tag is the PACKAGED version (the stamped one: `X.Y.Z-<full sha>` for a
`-{GIT_COMMIT}` chart), so two packagings of one chart publish two tags. A
version that is not a valid OCI tag (an unstamped build) is refused at run
time, never pushed. Registry credentials come from the Docker config, which
`docker login` / docker/login-action writes.

`bazel run --stamp <target> [-- <extra oras push flags>]`.
""",
    implementation = _chart_push_impl,
    executable = True,
    attrs = {
        "chart_name": attr.string(
            doc = "The chart's Chart.yaml `name:`; the push refuses a package that is some other chart.",
            mandatory = True,
        ),
        "package": attr.label(
            doc = "The `helm_chart` / `helm_package` target to push.",
            mandatory = True,
            providers = [HelmPackageInfo],
        ),
        "repository": attr.string(
            doc = "Host-qualified repository, no scheme and no tag: chart_registry_url(<chart>).",
            mandatory = True,
        ),
        "_chartconfig": attr.label(
            default = Label("//bazel/chartconfig"),
            executable = True,
            cfg = "exec",
        ),
        "_oras": attr.label(
            default = Label("//bazel/oras:oras_bin"),
            executable = True,
            allow_single_file = True,
            cfg = "target",
        ),
        "_runfiles_lib": attr.label(
            default = Label("@bazel_tools//tools/bash/runfiles"),
        ),
    },
)
