apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.serviceAccountName" . }}
  namespace: {{ include "controller.namespace" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
