load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cachemetrics",
    srcs = ["cachemetrics.go"],
    importpath = "aethermesh.dev/agent/internal/xds/cache/cachemetrics",
    visibility = ["//agent:__subpackages__"],
    deps = [
        "//common/udspath",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
    ],
)

go_test(
    name = "cachemetrics_test",
    size = "small",
    srcs = [
        "cachemetrics_test.go",
        "harnesscontract_test.go",
    ],
    embed = [":cachemetrics"],
    embedsrcs = ["cachemetrics.go"],
    deps = [
        "//common/udspath",
        "//test/harnesscontract",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_sdk_metric//metricdata",
    ],
)
