load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "manager",
    srcs = [
        "config.go",
        "flags.go",
        "logging.go",
        "manager.go",
    ],
    importpath = "aethermesh.dev/common/manager",
    visibility = ["//visibility:public"],
    deps = [
        "//common/log",
        "//common/telemetry/setup",
        "@com_github_go_logr_logr//:logr",
        "@com_github_spf13_cobra//:cobra",
        "@io_k8s_sigs_controller_runtime//:controller-runtime",
        "@io_k8s_sigs_controller_runtime//pkg/cache",
        "@io_k8s_sigs_controller_runtime//pkg/healthz",
        "@io_opentelemetry_go_contrib_bridges_otelslog//:otelslog",
    ],
)

go_test(
    name = "manager_test",
    srcs = ["telemetry_test.go"],
    embed = [":manager"],
    deps = [
        "//common/telemetry/setup",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
