load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "spire",
    srcs = [
        "bridge.go",
        "client.go",
        "converter.go",
        "metrics.go",
    ],
    importpath = "aethermesh.dev/agent/internal/spire",
    visibility = ["//agent:__subpackages__"],
    deps = [
        "//common/log",
        "@com_github_envoyproxy_go_control_plane_envoy//config/core/v3:core",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/transport_sockets/tls/v3:tls",
        "@com_github_spiffe_go_spiffe_v2//bundle/x509bundle",
        "@com_github_spiffe_go_spiffe_v2//exp/proto/spiffe/broker",
        "@com_github_spiffe_go_spiffe_v2//spiffeid",
        "@com_github_spiffe_go_spiffe_v2//spiffetls/tlsconfig",
        "@com_github_spiffe_go_spiffe_v2//svid/x509svid",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//metadata",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//types/known/anypb",
    ],
)

go_test(
    name = "spire_test",
    srcs = [
        "bridge_broker_test.go",
        "bridge_late_identity_test.go",
        "bridge_push_ordering_test.go",
        "bridge_reconnect_test.go",
        "bridge_test.go",
        "bridge_update_metrics_test.go",
        "converter_test.go",
        "node_svid_test.go",
    ],
    embed = [":spire"],
    deps = [
        "//common/spire/spiretest",
        "@com_github_envoyproxy_go_control_plane_envoy//extensions/transport_sockets/tls/v3:tls",
        "@com_github_spiffe_go_spiffe_v2//exp/proto/spiffe/broker",
        "@com_github_spiffe_go_spiffe_v2//spiffeid",
        "@com_github_spiffe_go_spiffe_v2//svid/x509svid",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_sdk_metric//metricdata",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//status",
    ],
)
